// This file is auto-generated by generate-env.js
export const environment = {
  production: false,
  IOT_ENDPOINT_URL: '/secret-url',
  IOT_KEY: 'fake-api-key',
  OPEN_WEATHER_KEY: '1184879409d98b72caf17821169093c9',
  SITE_LAT: 45.5,
  SITE_LON: -122.64,
  SITE_ELEVATION_M: 50
};
