const fs = require('fs');
require('dotenv').config();

const envConfigFile = `// This file is auto-generated by generate-env.js
export const environment = {
  production: ${process.env.NODE_ENV === 'production'},
  IOT_ENDPOINT_URL: '${process.env.IOT_ENDPOINT_URL || '/secret-url'}',
  IOT_KEY: '${process.env.IOT_KEY || 'fake-api-key'}',
  OPEN_WEATHER_KEY: '${process.env.OPEN_WEATHER_KEY || '1184879409d98b72caf17821169093c9'}',
  SITE_LAT: ${process.env.SITE_LAT || 45.5},
  SITE_LON: ${process.env.SITE_LON || -122.64},
  SITE_ELEVATION_M: ${process.env.SITE_ELEVATION_M || 50},
  GOOGLE_MAPS_API_KEY: '${process.env.GOOGLE_MAPS_API_KEY || ''}',
  NASA_API_KEY: '${process.env.NASA_API_KEY || ''}',
  APP_PIN: '${process.env.APP_PIN || '1234'}'
};
`;

fs.writeFileSync('./src/environments/environment.ts', envConfigFile);

const envProdConfigFile = `// This file is auto-generated by generate-env.js
export const environment = {
  production: true,
  IOT_ENDPOINT_URL: '${process.env.IOT_ENDPOINT_URL || '/secret-url'}',
  IOT_KEY: '${process.env.IOT_KEY || 'fake-api-key'}',
  OPEN_WEATHER_KEY: '${process.env.OPEN_WEATHER_KEY || '1184879409d98b72caf17821169093c9'}',
  SITE_LAT: ${process.env.SITE_LAT || 45.5},
  SITE_LON: ${process.env.SITE_LON || -122.64},
  SITE_ELEVATION_M: ${process.env.SITE_ELEVATION_M || 50},
  GOOGLE_MAPS_API_KEY: '${process.env.GOOGLE_MAPS_API_KEY || ''}',
  NASA_API_KEY: '${process.env.NASA_API_KEY || ''}',
  APP_PIN: '${process.env.APP_PIN || '1234'}'
};
`;

fs.writeFileSync('./src/environments/environment.development.ts', envConfigFile);
console.log('environment.ts generated successfully from .env');
